---
- name: Install Apache2
  hosts: webserver
  remote_user: hocine
  become: true
  become_user: root
  gather_facts: true

  tasks:
    - name: Install apache2
      package:
        name: apache2
        state: absent

