---
- name: Install PHP
  hosts: webserver
  remote_user: hocine
  become: true
  become_user: root
  gather_facts: true

  tasks:
    - name: Install PHP
      package:
        name: php
        state: absent

